### PR TITLE
Add font-display to eliminate Lighthouse warning

### PR DESCRIPTION
**Pull request by robmadole**
Ref https://github.com/FortAwesome/Font-Awesome/issues/16077

### CODE REVIEW

**Comment by mlwilkerson** [comment]
closes #108

**Review by mlwilkerson — APPROVED** [review]

**Comment by oleksandrzaiats** [comment]
Thank you for fixing it that quickly!
When could I expect a new version of the plugin released to get the changes?

**Comment by mlwilkerson** [comment]
I intend to release this week, which would include this change.

**Comment by oleksandrzaiats** [comment]
@mlwilkerson Thanks again! Looking forward to update it.

**Pull request merged**
