### PR TITLE
Multi-install notice copy/style

### PR DESCRIPTION
**Pull request by frrrances**

### CODE REVIEW

**Comment by frrrances** [comment]
@talbs Would love your eyes on this copy (if you have a parsec).

**Comment by frrrances** [comment]
Here it is in context... 
Screen Shot 2020-01-24 at 4 28 18 PM

**Comment by frrrances** [comment]
Thanks for the additional clarifying info, @mlwilkerson. A few questions: 

1. I thought this message only appeared when the user-installed version in the plugin list was not the newest in the WP installation, so it would only apply in cases where we were using another plugin version to do settings (and all the other things). So if they updated their user-installed plugin, the plugin in the list would be at the latest and the warning message would disappear... right?
2. Right, but the Font Awesome plugin would only appear in this list (and show the warning) if the user installed it, right?
3. Yeah, I was simplifying since any major changes to the stuff underlying the plugin would result in a new major version. We can make these kind of granular details clear in any supporting docs for those really needing them.

Let me know if it would help to chat this out...

**Comment by mlwilkerson** [comment]
@frrrances responding to your points:

1. correct.

2. correct.
    And that's why I can understand why our guidance might be to upgrade the one they installed. What I'm suggesting, though, is that they might not realize that it's unnecessary to have both installed. They don't need to upgrade in order to get rid of the warning. They could also get rid of the warning by uninstalling the plugin from the plugins list and just letting plugin-sigma handle things.
    It's possible that they got themselves into this situation because of _confusion_ --thinking they needed to install the plugin manually, despite plugin-sigma's installation--rather than intentionality. If it's confusion, then we're either side-stepping or deepening that confusion by suggesting that they upgrade the plugin.
    My concession, though, is that our goal here may not be to help them clearly understanding what's going. The goal may be more pragmatic--keep things up to date, and get rid of warnings. I defer to you to determine which goal is more appropriate here.

3. cool

**Comment by frrrances** [comment]
Ok! Confusion vanquished and PR headed to mergetown!

**Pull request merged**
