### PR TITLE
update the composer.lock

### PR DESCRIPTION
**Pull request by jasonlundien**

### CODE REVIEW

**Comment by jasonlundien** [comment]
@mlwilkerson --  Rob and I were getting the wordpress dev up and running locally.
And It would NOT let me move any further without updating this file.

**Review by mlwilkerson — COMMENTED** [review]
Yeah, looking at the GitHub Actions failures, it looks like something more significant has changed related to dependencies for PHP Unit testing. Seems like every time I do a significant round of development in this repo, I've got to wrestle with that sort of problem again. I assume it's going to take some tedious trial and error to resolve.

Are you need to release a change to the plugin soon? Or are you just trying to work with the repo in local dev? If the latter, did you get it working well enough for you for now?

**Comment by robmadole** [comment]
@mlwilkerson we were just using local dev and caught a problem. Jason and I were able to get it going far enough to accomplish our task. So this can defer until we need to cut a release.

**Comment by mlwilkerson** [comment]
Closing since I've merged in an alternative way of dealing with this. Turns out: what we needed was a more clear strategy for keeping track of php version specific composer configs that would run in the various development environment containers. And probably, the fact that there were some issues reported here had to do with using a version of php in the host environment that didn't match the version that would have been running inside the the container--and using this composer config. I've updated the `DEVELOPMENT.md` with more detailed explanation about dealing with various php versions--usually only within containers, not the host environment. And the new docker configurations use php version specific composer configs within each of those environments.

**Pull request closed without merging**
